"""add_accepted_offer_field

Revision ID: 2431a051cec7
Revises: dcce2a52cd6f
Create Date: 2026-03-16 08:22:57.242458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2431a051cec7'
down_revision: Union[str, Sequence[str], None] = 'dcce2a52cd6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_sessions_session_token'), table_name='admin_sessions')
    op.drop_table('admin_sessions')
    op.drop_index(op.f('ix_materials_lesson_id'), table_name='materials')
    op.drop_constraint(op.f('materials_lesson_id_fkey'), 'materials', type_='foreignkey')
    op.create_foreign_key(None, 'materials', 'lessons', ['lesson_id'], ['id'])
    op.add_column('users', sa.Column('accepted_offer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'accepted_offer')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.create_foreign_key(op.f('materials_lesson_id_fkey'), 'materials', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_materials_lesson_id'), 'materials', ['lesson_id'], unique=False)
    op.create_table('admin_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('admin_sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_sessions_pkey')),
    sa.UniqueConstraint('session_token', name=op.f('admin_sessions_session_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_admin_sessions_session_token'), 'admin_sessions', ['session_token'], unique=False)
    # ### end Alembic commands ###
